configuration:
  runtime: concord-v2

flows:
  default:
    - log: |
        org: ${projectInfo.orgName}
        clusterId: ${clusterId}

    # only top-level variables can be returned as outVars
    - call: anotherFlow
      out:
        - result

  anotherFlow:
    - set:
        result: "Hello, ${projectInfo.orgName}/${clusterId}"
